[general]
import = [
"~/.config/alacritty/apparence.toml",  
"~/.config/alacritty/colors.toml",
"~/.config/alacritty/cursor.toml",
"~/.config/alacritty/font.toml",
"~/.config/alacritty/mouse.toml",
]
